title: Corona Info Nepal
email: budhram.gurung01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Get the reliable and authentic information regarding COVID-19 disease
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coronainfonepal.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /news/:year/:month/:day/:title/
  
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
